name: flutter_chess
description: A wholesome chess game package
version: 0.1.0+1


environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

dependencies:
  equatable: ^2.0.5

flutter:
  assets:
    - assets/images/black/
    - assets/images/white/
